# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u59d3\u540d')),
                ('password', models.CharField(max_length=128, verbose_name='\u5bc6\u7801')),
                ('type', models.IntegerField(choices=[(0, '\u6280\u672f'), (1, '\u6d4b\u8bd5'), (2, '\u7ecf\u7406')], default=0, verbose_name='\u804c\u4f4d')),
                ('enterTime', models.DateTimeField(auto_now_add=True, verbose_name='\u5165\u804c\u65f6\u95f4')),
                ('qq', models.CharField(default='', max_length=12, verbose_name='QQ')),
                ('avatar', models.ImageField(null=True, upload_to='media', verbose_name='\u5934\u50cf')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
