# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u59d3\u540d')),
                ('type', models.IntegerField(choices=[(0, '\u6280\u672f'), (1, '\u6d4b\u8bd5'), (2, '\u7ecf\u7406')], verbose_name='\u804c\u4f4d')),
                ('enterTime', models.DateTimeField(auto_now_add=True, verbose_name='\u5165\u804c\u65f6\u95f4')),
                ('qq', models.CharField(max_length=12, verbose_name='QQ')),
                ('avatar', models.ImageField(upload_to='media', verbose_name='\u5934\u50cf')),
            ],
        ),
    ]
