# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media', verbose_name='\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(default='', max_length=12, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(0, '\u6280\u672f'), (1, '\u6d4b\u8bd5'), (2, '\u7ecf\u7406')], default=0, verbose_name='\u804c\u4f4d'),
        ),
    ]
